id: PB79A9191
initial_creation_type: input
source_metadata:
  Title: Tattvasiddhiḥ
  Editor: '-'
  Publisher: '-'
  Place of Publication: '-'
  Year: '-'
  Tattvasiddhiḥ:
    Text Version: ''
    Input Personnel: ''
    Input Date: ''
    Proof Reader: ''
    Supplier: ''
    Sponsor: ''
created_at: '2022-03-08T16:59:11.898414'
last_modified_at: '2022-03-08T16:59:11.898422'
